name = input("Enter your name: ")
age = int(input("Enter your age: "))
dob = input("Enter your DateofBirth: ")
phone_number = input("Enter your phone number: ")

print('Personal Details:')
print(f"Your Name : {name}")
print(f"Your Age : {age}")
print(f"Your DateofBirth : {dob}")
print(f"Your PhoneNumber : {phone_number}")
